polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('home/', views.base, name='base')
]

users/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    ]

zagusweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('users/', include('users.urls'))
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user} Profile'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse


def base(request):
    return render(request, 'polls/base.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from .forms import UserRegistrationForm
from django.http import HttpResponse


#imports special for email verification
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text, force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created! Log In!')
            return redirect("polls:base")

    else:
        form = UserRegistrationForm()
        return render(request, 'users/register.html', {'form': form})

    form = UserRegistrationForm
    return render(request=request,
                  template_name="users/register.html",
                  context={"form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully")
    return redirect("polls:base")


def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f'You are now logged in as {username}')
                return redirect('polls:base')
            else:
                messages.error(request, 'Invalid user name or password')
        else:
            messages.error(request, 'Invalid user name or password')
    form = AuthenticationForm()
    return render(request=request, template_name='users/login.html', context={"form": form})


"""def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        context = {'uidb64':uidb64, 'token':token}
        return render(request, 'users/acc_activate.html', context)
    else:
        return HttpResponse('Activation link is invalid!')"""

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css'%}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Title</title>
</head>
<body>
    <div class="w3-bar w3-black topnav">
        <a href="{% url 'polls:base' %}" class="w3-bar-item w3-button w3-mobile w3-purple">Home</a>
        <a href="#" class="w3-bar-item w3-button w3-mobile">Polls</a>
        <a href="#" class="w3-bar-item w3-button w3-mobile">Food</a>
        <a href="#" class="w3-bar-item w3-button w3-mobile">Games</a>
        <div class="w3-dropdown-hover w3-mobile">
            <button class="w3-button">Dropdown <i class="fa fa-caret-down"></i></button>
            <div class="w3-dropdown-content w3-bar-block w3-dark-grey">
                <a href="#" class="w3-bar-item w3-button w3-mobile">Link 1</a>
                <a href="#" class="w3-bar-item w3-button w3-mobile">Link 2</a>
                <a href="#" class="w3-bar-item w3-button w3-mobile">Link 3</a>
            </div>
        </div>
        <div>
            {% if user.is_authenticated %}
                <a class="w3-bar-item w3-button w3-mobile w3-right w3-purple" href="{% url 'users:logout' %}">Logout</a>
                <a class="w3-bar-item w3-button w3-mobile w3-right w3-purple" href="#">Profile</a>
            {% else%}
                <a class="w3-bar-item w3-button w3-mobile w3-right w3-purple" href="{% url 'users:login' %}">Login</a>
                <a class="w3-bar-item w3-button w3-mobile w3-right w3-purple" href="{% url 'users:register' %}">Register</a>
            {% endif %}
        </div>
    </div>
        {% if messages %}
            {% for message in messages %}
                {% if 'success' in message.tags %}
                    <div class="alert alert-success">
                        {{message}}
                    </div>
                {% elif 'info' in message.tags %}
                    <div class="alert alert-info">
                        {{message}}
                    </div>
                {% else %}
                    <div class="alert alert-danger">
                        {{message}}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

users/templates/users/acc_activate.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/login.html
{% extends "polls/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
<div class ="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class ="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-2">
        <small class="text-muted">
            Need an account? <a class="ml-2"  href="{% url 'users:register' %}">Sign Up</a>
        </small>
    </div>
</div>
{% endblock content %}

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/users/register.html
{% extends 'polls/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button style="background-color:green" class="w3-button" type="submit">Sign Up</button>
    </form>
<br>
    <div>If you already have an account <a href="/login" target="blank"><strong>login</strong></a> instead.</div>

{% endblock content %}